<a href="https://colab.research.google.com/github/tom-brash/handson-ml2/blob/master/workbooks/ch16/testing_with_open_ai_gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install transformers

     |████████████████████████████████| 757kB 3.5MB/s 
     |████████████████████████████████| 890kB 16.4MB/s 
     |████████████████████████████████| 1.1MB 23.3MB/s 
     |████████████████████████████████| 3.0MB 31.5MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=41a06931c333abed887497a572616625ba1f8e37735707195a2dd60f050fe4e7
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import TFOpenAIGPTLMHeadModel

In [4]:
model = TFOpenAIGPTLMHeadModel.from_pretrained('openai-gpt')

All model checkpoint weights were used when initializing TFOpenAIGPTLMHeadModel.

All the weights of TFOpenAIGPTLMHeadModel were initialized from the model checkpoint at openai-gpt.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use TFOpenAIGPTLMHeadModel for predictions without further training.


In [5]:
from transformers import OpenAIGPTTokenizer
tokenizer = OpenAIGPTTokenizer.from_pretrained('openai-gpt')

ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.


In [6]:
prompt_text = 'Hey, how\'s it going?'
encoded_prompt = tokenizer.encode(prompt_text, 
                                  add_special_tokens=False, 
                                  return_tensors='tf')

encoded_prompt

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[2229,  240,  718,  256,  252,  507,  797,  257]], dtype=int32)>

In [7]:
num_sequences = 2
length = 200

generated_sequences = model.generate(input_ids=encoded_prompt,
                                     do_sample=True,
                                     max_length=length+len(encoded_prompt),
                                     temperature=1.0,
                                     top_k=0,
                                     top_p=0.9,
                                     repetition_penalty=1.0,
                                     num_return_sequences=num_sequences)

generated_sequences

<tf.Tensor: shape=(2, 201), dtype=int32, numpy=
array([[ 2229,   240,   718,   256,   252,   507,   797,   257,   244,
         6724,  1347,   551,   617,   806,   487,   509,  1779,   491,
          481,  2833,   239, 40477,   547,  1934,  6770,   240,   244,
         1614,   240,   249,   825,   239,   806,   640,  9621,   488,
         2686,   257,   244, 40477,   244,  1036,  1313,   562,  7160,
          491,   754, 38033,   240,   244,   603,  6724,   240,   244,
          600,   804,   580,   551,   500,   246,  1026,  1571,   239,
          244, 40477,   249,  1275,   485,  1178,   547, 10903,   240,
          507,   509,  3125,   240,   249,   509,   620,  2503,   670,
         9621,   239,   244,   862,   249,  1777,   600,   761,   500,
          870,   983,   240,   249,   966,   485,   727,   841,   562,
          246,  1000,   239,   244, 40477,   487,  1246,   510,   246,
         7619,  1242,   239,   244,  1439,   240,   249,  1839,   600,
          812,   580,   239, 

In [8]:
for seq in generated_sequences:
  text = tokenizer.decode(seq, clean_up_tokenization_spaces=True)
  print(text)
  print('-'*80)

hey, how's it going? " brandon called out from where he was sitting at the counter. 
 my shoulders slumped, " fine, i think. where are allie and nick? " 
 " being held for questioning at their sentencing, " said brandon, " they 'll be out in a few minutes. " 
 i tried to keep my composure, it was difficult, i was so worried about allie. " well i hope they're in good hands, i need to get away for a while. " 
 he gave me a genuine smile. " yeah, i guess they will be. " 
 " you don't seem so cool with me leaving, " i said. 
 " yeah, i'm trying to be supportive, but i don't know what i'm doing. " 
 i leaned forward and put my elbows on the counter. " what is your problem, brandon? " 
 he grimaced. " i don't like you being with ethan. i don't like him being around
--------------------------------------------------------------------------------
hey, how's it going?'he asked the inmate, trying to sound pleasant. 
'you could say the same about me,'the inmate replied. he felt more cool air ruff